version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"  # Expose Flask web app on port 5000
    volumes:
      - .:/app  # Mount current directory to container for development
    networks:
      - shared_network

networks:
  shared_network:
    external:
      name: red_compartida
