version: '3.8'

services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "8080:8080"  # Exponer Flask en el puerto 8080
    volumes:
      - .:/api  # Monta el directorio actual en el contenedor para el desarrollo

networks:
  default:
    external:
      name: red_compartida